services:
    backend:
        build: ./backend
        env_file: .env
        depends_on:
            - redis
        volumes:
            - sqlite_data:/root/data
        environment:
            - REDIS_CONNECTION_URL=redis:6379/0
            - SQLITE_PATH=/root/data/my_database.db

    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - redis_data:/root/cashe
volumes:
    sqlite_data:
        driver: local
    redis_data:
        
