#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const version = pkg.version || '0.0.0';

const outDir = path.join(root, 'src', 'environments');
fs.mkdirSync(outDir, { recursive: true });

const outFile = path.join(outDir, 'version.ts');
const content = `// AUTO-GENERATED by scripts/generate-version.js — do not edit manually.\nexport const APP_VERSION = '${version}';\n`;

const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : '';
if (existing.trim() === content.trim()) {
  process.exit(0);
}

fs.writeFileSync(outFile, content, 'utf8');
console.log(`[generate-version] Wrote APP_VERSION="${version}" to src/environments/version.ts`);
